# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

glsCpp <- function(Y, Z, Z2, H, h, A0, B0, C0, Omega0, break_pts, r, n_iter) {
    .Call('_narwhalCA_glsCpp', PACKAGE = 'narwhalCA', Y, Z, Z2, H, h, A0, B0, C0, Omega0, break_pts, r, n_iter)
}

glsConstCpp <- function(Y, Z, Z2, H, h, A0, B0, C0, Omega0, break_pts, r, n_iter) {
    .Call('_narwhalCA_glsConstCpp', PACKAGE = 'narwhalCA', Y, Z, Z2, H, h, A0, B0, C0, Omega0, break_pts, r, n_iter)
}

vecm <- function(Z0, Z1, Z2, r, dt, intercept) {
    .Call('_narwhalCA_vecm', PACKAGE = 'narwhalCA', Z0, Z1, Z2, r, dt, intercept)
}

johansenCpp <- function(Z0, Z1, Z2, r, dt, intercept) {
    .Call('_narwhalCA_johansenCpp', PACKAGE = 'narwhalCA', Z0, Z1, Z2, r, dt, intercept)
}

